from pathlib import Path

from docx import Document
from pptx import Presentation
from pptx.util import Inches, Pt

from .analysis_service import from_json
from .file_service import GENERATED_FOLDER


def make_project_folder(project_id: int) -> Path:
    folder = GENERATED_FOLDER / f"project_{project_id}"
    folder.mkdir(parents=True, exist_ok=True)
    return folder


def create_word_proposal(project) -> str:
    folder = make_project_folder(project.id)
    file_path = folder / f"{project.client_name.replace(' ', '_')}_proposal.docx"

    analysis = from_json(project.analysis_json)
    insights = from_json(project.insights_json)

    document = Document()
    document.add_heading(f"Proposal for {project.client_name}", 0)
    document.add_paragraph(f"Industry: {project.industry}")
    document.add_paragraph(f"Project Type: {project.project_type}")
    document.add_paragraph(f"Business Goal: {project.business_goal}")

    document.add_heading("Executive Summary", level=1)
    document.add_paragraph(insights.get("executive_summary", "Not generated yet."))

    document.add_heading("Key Data Findings", level=1)
    document.add_paragraph(insights.get("data_insights", "No data insights available."))
    document.add_paragraph(f"Total records analyzed: {analysis.get('total_rows', 0)}")
    document.add_paragraph(f"Retention risk: {analysis.get('retention_risk', 'Not available')}")
    document.add_paragraph(f"Average spend: {analysis.get('average_spend', 0)}")

    document.add_heading("Client Pain Points", level=1)
    document.add_paragraph(insights.get("client_pain_points", "Not available."))

    document.add_heading("Recommended Solution", level=1)
    document.add_paragraph(insights.get("recommendations", "Not available."))

    document.add_heading("Risks", level=1)
    document.add_paragraph(insights.get("risks", "Not available."))

    document.add_heading("Next Steps", level=1)
    document.add_paragraph(insights.get("next_steps", "Not available."))

    document.save(file_path)
    return str(file_path)


def add_bullet_slide(prs, title: str, bullets: list[str]):
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    slide.shapes.title.text = title
    body = slide.shapes.placeholders[1].text_frame
    body.clear()

    for bullet in bullets:
        paragraph = body.add_paragraph()
        paragraph.text = bullet
        paragraph.font.size = Pt(20)


def create_powerpoint_deck(project) -> str:
    folder = make_project_folder(project.id)
    file_path = folder / f"{project.client_name.replace(' ', '_')}_deck.pptx"

    analysis = from_json(project.analysis_json)
    insights = from_json(project.insights_json)

    prs = Presentation()

    title_slide = prs.slides.add_slide(prs.slide_layouts[0])
    title_slide.shapes.title.text = f"{project.client_name} Proposal"
    title_slide.placeholders[1].text = "Generated by ClientIQ"

    add_bullet_slide(
        prs,
        "Business Challenge",
        [project.business_goal, insights.get("client_pain_points", "Pain points not available.")],
    )

    add_bullet_slide(
        prs,
        "Data Snapshot",
        [
            f"Total records: {analysis.get('total_rows', 0)}",
            f"Retention risk: {analysis.get('retention_risk', 'Not available')}",
            f"Inactive customers: {analysis.get('inactive_customers', 0)}",
            f"High complaint customers: {analysis.get('high_complaint_customers', 0)}",
        ],
    )

    add_bullet_slide(
        prs,
        "Recommended Strategy",
        [insights.get("recommendations", "Recommendations not available.")],
    )

    add_bullet_slide(
        prs,
        "Next Steps",
        [insights.get("next_steps", "Next steps not available.")],
    )

    prs.save(file_path)
    return str(file_path)

